### ISSUE TITLE
Wrong dependencies for Mekanism: Tools

### ISSUE THREAD

**Issue by Alexaario** [GalacticSilver/TGP2#1]
"You must include the right dependencies for Mekanism: Tools:

Only compatible with Mekanism 1.12.2-9.8.3.390 (you have 1.12.2-9.8.2.3.8.9)"

**Comment by Alexaario** [comment]
I changed it to the newest mekanism version and now it says it needs an older (original) version for Mekanism: Generators

**Comment by GalacticSilver** [comment]
This is a known issue and a fix is coming as soon as possible (I am currently figuring out an uploading error), you can fix this by **only** updating Mekanism and none of it's other side mods.

**Comment by Alexaario** [comment]
To the latest version?

**Comment by GalacticSilver** [comment]
Yes.

**Comment by GalacticSilver** [comment]
If you find any more issues please feel free to join the TGP discord server: https://discord.gg/KpFYsqF
